# this is config file for Auto Request Review
# See https://github.com/marketplace/actions/auto-request-review for more info.

reviewers:
  # The default reviewers if not assigned specifically 
  defaults:
    - group1 # group

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    group1:
      - YimingPan-Code
      - abdullaTigerGraph

files:
  # All review request will be sent to the following groups/people.
  '**':
    - group1

options:
  # ignore draft PRs
  ignore_draft: true
  # ignore PRs with title contains specific keywords
  ignored_keywords:
    - DO NOT REVIEW
  # request reviews to all other members in the same group
  enable_group_assignment: true
