# this is config file for Auto Request Review
# See https://github.com/marketplace/actions/auto-request-review for more info.

reviewers:
  # The default reviewers if not assigned specifically 
  defaults:
    - primary
    - secondary
    - tertiary
  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    primary:
      - RobRossmiller-TG
      - wyattjoynertg
      - parkererickson-tg
      - victorleeTG
    # secondary:
    #   - RobRossmiller-TG
    #   - wyattjoynertg
    # tertiary:
    #   - victorleeTG

files:
  # All review request will be sent to the following groups/people.
  '**':
    - primary
    # - secondary
    # - tertiary

options:
  # ignore draft PRs
  ignore_draft: true
  # ignore PRs with title contains specific keywords
  ignored_keywords:
    - DO NOT REVIEW
  # request reviews to all other members in the same group
  enable_group_assignment: true
